name: tuxpusheraf
base: core22
version: '1.0'
summary: This one is better, featuring Tux & Friends!
description: |
  Just move around your mouse and click to release a coin.

  Getting a gold coin in a silver slot rewards you 2x silver coins.
  Getting a gold coin in a gold slot rewards you 2x gold coins.
  Getting a tux in a slot when you already have the tux gives you 6x gold coins and 6x silver coins.

  Left Click = Release coin.
  Right Click = Show/Hide cursor.
  C = Orthographic/Perspective.
  F = FPS to console.

grade: stable
confinement: strict

architectures:
  - build-on: [amd64]
    build-for: [amd64]
  - build-on: [arm64]
    build-for: [arm64]
  - build-on: [armhf]
    build-for: [armhf]

apps:
  tuxpusheraf:
    extensions: [gnome]
    command: tuxpusheraf
    plugs:
    - desktop
    - desktop-legacy
    - gsettings
    - opengl
    - wayland
    - x11

parts:
  tuxpusheraf:
    source: https://github.com/mrbid/tuxpusheraf
    source-type: git
    plugin: make
    source-subdir: snap
    build-packages:
    - libglfw3-dev
    stage-packages:
    - libglfw3
    - libgles2